// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQPR0aC6CZauyZ_FaGNlWsEoe_q5GjrVU',
    appId: '1:129868564610:web:0ecefead1bd9273d300c9b',
    messagingSenderId: '129868564610',
    projectId: 'exam-64c9c',
    authDomain: 'exam-64c9c.firebaseapp.com',
    storageBucket: 'exam-64c9c.appspot.com',
    measurementId: 'G-XDL2HWLQLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJndRLiXc-rBCQCcOPD_mPk4XhyW7ZKcI',
    appId: '1:129868564610:android:994127a0bd7b1263300c9b',
    messagingSenderId: '129868564610',
    projectId: 'exam-64c9c',
    storageBucket: 'exam-64c9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsnI6GMDSf9tpq5BodaaAzFhnmCjT43o',
    appId: '1:129868564610:ios:daeb392ee5b85688300c9b',
    messagingSenderId: '129868564610',
    projectId: 'exam-64c9c',
    storageBucket: 'exam-64c9c.appspot.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGMfn_iUFObVEl_BDV56XQVr-c8SizjWU',
    appId: '1:109025219801:ios:0004e9fed25144b7875ac8',
    messagingSenderId: '109025219801',
    projectId: 'exam-54d2e',
    storageBucket: 'exam-54d2e.appspot.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZaaUIGtdUsVNC5bCkzMtfykeIDNAS1I',
    appId: '1:109025219801:web:9f17da73714c8f8b875ac8',
    messagingSenderId: '109025219801',
    projectId: 'exam-54d2e',
    authDomain: 'exam-54d2e.firebaseapp.com',
    storageBucket: 'exam-54d2e.appspot.com',
    measurementId: 'G-DGEHYW70YJ',
  );

}